// 別府市エリアマッピングデータ - 完全版
// このデータをpopulate-beppu-area-mapping.tsのbeppuAreaData配列に置き換えてください

export const completeBeppuAreaData = [
  // ⑨ 青山中学校区
  { school_district: '青山中学校', region_name: '南立石一区', distribution_areas: '⑨㊷', other_region: '別府駅周辺' },
  { school_district: '青山中学校', region_name: '南立石二区', distribution_areas: '⑨㊸', other_region: '鉄輪線より下' },
  { school_district: '青山中学校', region_name: '南立石生目町', distribution_areas: '⑨', other_region: null },
  { school_district: '青山中学校', region_name: '南立石板地町', distribution_areas: '⑨㊷', other_region: '別府駅周辺' },
  { school_district: '青山中学校', region_name: '南立石八幡町', distribution_areas: '⑨㊸', other_region: '鉄輪線より下' },
  { school_district: '青山中学校', region_name: '堀田', distribution_areas: '⑨', other_region: null },
  { school_district: '青山中学校', region_name: '南荘園町', distribution_areas: '⑨㊸', other_region: '鉄輪線より下' },
  { school_district: '青山中学校', region_name: '観海寺', distribution_areas: '⑨㊸', other_region: '鉄輪線より下' },
  { school_district: '青山中学校', region_name: '鶴見園町', distribution_areas: '⑨㊸', other_region: '鉄輪線より下' },
  { school_district: '青山中学校', region_name: '扇山', distribution_areas: '⑨㊶', other_region: null },
  { school_district: '青山中学校', region_name: '荘園', distribution_areas: '⑨㊸', other_region: '鉄輪線より下' },
  { school_district: '青山中学校', region_name: '板地町', distribution_areas: '⑨㊷', other_region: '別府駅周辺' },
  { school_district: '青山中学校', region_name: '本町', distribution_areas: '⑨㊷', other_region: '別府駅周辺' },
  { school_district: '青山中学校', region_name: '八幡町', distribution_areas: '⑨㊷', other_region: '別府駅周辺' },
  
  // ⑩ 中部中学校区
  { school_district: '中部中学校', region_name: '荘園北町', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '緑丘町', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '東荘園4丁目', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '東荘園5丁目', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '東荘園6丁目', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '東荘園7丁目', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '東荘園8丁目', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '東荘園9丁目', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '鶴見', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '荘園', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '上野口町', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '天満町', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '東荘園1丁目', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '東荘園2丁目', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '東荘園3丁目', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '石垣東1丁目', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '石垣東2丁目', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '石垣東3丁目', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '石垣西1丁目', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '石垣西2丁目', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '石垣西3丁目', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '駅前町', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '駅前本町', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '北浜1丁目', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '北浜2丁目', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '北浜3丁目', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '北的ヶ浜町', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '京町', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '幸町', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '新港町', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '野口中町', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '野口元町', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '富士見町', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '南的ヶ浜町', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '餅ヶ浜町', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '元町', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '弓ヶ浜町', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
  { school_district: '中部中学校', region_name: '若草町', distribution_areas: '⑩㊸', other_region: '鉄輪線より下' },
];

console.log(`Total mappings: ${completeBeppuAreaData.length}`);
